import random
from itertools import combinations


def sample_3sat_formula(num_variables: int,
                        num_clauses: int,
                        rng: random.Random) -> list[list[int]]:
    """Sample a random 3-CNF formula.

    Args:
        num_variables: Number of Boolean variables.
        num_clauses: Number of three-literal clauses.
        rng: Random generator used for reproducible sampling.

    Returns:
        Randomly sampled 3-CNF formula encoded as signed integer literals.
    """

    if num_variables < 3:
        raise ValueError('A 3-SAT formula requires at least three variables.')

    formula = []
    for i in range(num_clauses):
        variables = rng.sample(range(1, num_variables + 1), 3)
        formula.append([variable if rng.choice([True, False]) else -variable for variable in variables])

    return formula


def parse_response(response: str,
                   label: str,
                   no_solution: str) -> list[str] | None:
    """Parse a labelled comma-separated model response.

    Args:
        response: Raw response generated by the model.
        label: Required response label for the active framing.
        no_solution: Exact value used to declare that no solution exists.

    Returns:
        Listed response values or None when the response declares no solution.

    Raises:
        ValueError: If the response does not use the required label.
    """

    response = response.strip()
    prefix = f'{label}:'
    if not response.startswith(prefix):
        raise ValueError(f'Response must start with {prefix}')

    response_values = response.removeprefix(prefix).strip()
    if response_values == no_solution:
        return None
    if not response_values:
        return []
    return [value.strip() for value in response_values.split(',')]


def parse_assignment(response: str,
                     label: str,
                     no_solution: str,
                     num_variables: int) -> list[int] | None:
    """Parse an assignment response into its true variable numbers.

    Args:
        response: Raw response generated by the model.
        label: Required response label for the CNF framing.
        no_solution: Exact value used to declare that no solution exists.
        num_variables: Number of variables that may be assigned true.

    Returns:
        True variable numbers or None when the response declares no solution.

    Raises:
        ValueError: If the assignment contains invalid or repeated variables.
    """

    response_values = parse_response(response, label, no_solution)
    if response_values is None:
        return None

    try:
        true_variables = [int(value) for value in response_values]
    except ValueError as error:
        raise ValueError('Assignment values must be integers.') from error

    if any(variable < 1 or variable > num_variables for variable in true_variables):
        raise ValueError('Assignment contains an unknown variable.')
    if len(set(true_variables)) != len(true_variables):
        raise ValueError('Assignment contains repeated variables.')
    return true_variables


def parse_menu(response: str,
               label: str,
               no_solution: str,
               food_items: list[str]) -> list[str] | None:
    """Parse a menu response into canonical food-item names.

    Args:
        response: Raw response generated by the model.
        label: Required response label for the MENU framing.
        no_solution: Exact value used to declare that no solution exists.
        food_items: Food items available to the player in this instance.

    Returns:
        Selected canonical food-item names or None for a no-solution response.

    Raises:
        ValueError: If the menu contains unavailable or repeated food items.
    """

    response_values = parse_response(response, label, no_solution)
    if response_values is None:
        return None

    food_item_lookup = {food_item.casefold(): food_item for food_item in food_items}
    menu_items = []
    for response_value in response_values:
        food_item = food_item_lookup.get(response_value.casefold())
        if food_item is None:
            raise ValueError(f'Menu contains unknown food item: {response_value}')
        menu_items.append(food_item)

    if len(set(menu_items)) != len(menu_items):
        raise ValueError('Menu contains repeated food items.')
    return menu_items


def parse_menu_update(response: str,
                      response_format: dict[str, str],
                      food_items: list[str]) -> dict[str, list[str] | str]:
    """Parse one structured menu-repair response.

    Args:
        response: Raw response generated by the model.
        response_format: Language-specific labels and no-change value.
        food_items: Food items available to the player in this instance.

    Returns:
        Explanation text plus canonical additions and removals.

    Raises:
        ValueError: If the response does not use the required three-line format.
    """

    response = response.strip()
    lines = [line for line in response.splitlines() if line.strip()]
    expected_labels = [
        response_format['add_label'],
        response_format['remove_label'],
        response_format['explanation_label']
    ]
    if len(lines) != len(expected_labels):
        raise ValueError(
            f"Response must contain exactly these lines: {', '.join(expected_labels)}."
        )

    values = {}
    for line, label in zip(lines, expected_labels):
        prefix = f'{label}:'
        if not line.startswith(prefix):
            raise ValueError(f'Response line must start with {prefix}')
        values[label] = line.removeprefix(prefix).strip()

    explanation = values[response_format['explanation_label']]
    if not explanation:
        raise ValueError(f"{response_format['explanation_label']} must not be empty.")

    food_item_lookup = {food_item.casefold(): food_item for food_item in food_items}

    def parse_items(value: str) -> list[str]:
        if value == response_format['no_change']:
            return []
        if not value:
            raise ValueError(f"Use {response_format['no_change']} when no menu items change.")

        items = []
        for item in value.split(','):
            food_item = food_item_lookup.get(item.strip().casefold())
            if food_item is None:
                raise ValueError(f'Menu contains unknown food item: {item.strip()}')
            items.append(food_item)

        if len(set(items)) != len(items):
            raise ValueError('A menu item may appear only once per update.')
        return items

    additions = parse_items(values[response_format['add_label']])
    removals = parse_items(values[response_format['remove_label']])
    if set(additions).intersection(removals):
        raise ValueError('A menu item cannot be added and removed in the same update.')

    return {
        'explanation': explanation,
        'additions': additions,
        'removals': removals
    }


def parse_assignment_update(response: str,
                            response_format: dict[str, str],
                            num_variables: int) -> dict[str, list[int] | str]:
    """Parse one structured truth-assignment repair response.

    Args:
        response: Raw response generated by the model.
        response_format: Language-specific labels and no-change value.
        num_variables: Number of variables in the formula.

    Returns:
        Explanation text plus variables set to true and false.

    Raises:
        ValueError: If the response does not use the required three-line format.
    """

    response = response.strip()
    lines = [line for line in response.splitlines() if line.strip()]
    expected_labels = [
        response_format['set_true_label'],
        response_format['set_false_label'],
        response_format['explanation_label']
    ]
    if len(lines) != len(expected_labels):
        raise ValueError(
            f"Response must contain exactly these lines: {', '.join(expected_labels)}."
        )

    values = {}
    for line, label in zip(lines, expected_labels):
        prefix = f'{label}:'
        if not line.startswith(prefix):
            raise ValueError(f'Response line must start with {prefix}')
        values[label] = line.removeprefix(prefix).strip()

    explanation = values[response_format['explanation_label']]
    if not explanation:
        raise ValueError(f"{response_format['explanation_label']} must not be empty.")

    def parse_variables(value: str) -> list[int]:
        if value == response_format['no_change']:
            return []
        if not value:
            raise ValueError(f"Use {response_format['no_change']} when no variables change.")

        try:
            variables = [int(variable.strip()) for variable in value.split(',')]
        except ValueError as error:
            raise ValueError('Variable identifiers must be integers.') from error

        if any(variable < 1 or variable > num_variables for variable in variables):
            raise ValueError('Update contains an unknown variable.')
        if len(set(variables)) != len(variables):
            raise ValueError('A variable may appear only once per update.')
        return variables

    set_true = parse_variables(values[response_format['set_true_label']])
    set_false = parse_variables(values[response_format['set_false_label']])
    if set(set_true).intersection(set_false):
        raise ValueError('A variable cannot be set both true and false in one update.')

    return {
        'explanation': explanation,
        'set_true': set_true,
        'set_false': set_false
    }


def evaluate_formula(formula: list[list[int]],
                     true_variables: list[int]) -> list[bool]:
    """Evaluate every clause under a partial true-variable representation.

    Args:
        formula: 3-CNF formula encoded as signed integer literals.
        true_variables: Variables assigned true; all other variables are false.

    Returns:
        Satisfaction status for every clause in formula order.
    """

    true_variable_set = set(true_variables)
    return [any(literal in true_variable_set if literal > 0 else -literal not in true_variable_set
                for literal in clause)
            for clause in formula]


def evaluate_preferences(preferences: list[dict],
                         menu_items: list[str]) -> list[bool]:
    """Evaluate every participant under a menu selection.

    Args:
        preferences: Participant likes and dislikes derived from formula clauses.
        menu_items: Food items placed on the menu.

    Returns:
        Satisfaction status for every participant in preference order.
    """

    menu_item_set = set(menu_items)
    return [bool(menu_item_set.intersection(preference['likes'])
                 or set(preference['dislikes']).difference(menu_item_set))
            for preference in preferences]


def is_satisfying_assignment(formula: list[list[int]],
                             assignment: dict[int, bool]) -> bool:
    """Check whether an assignment satisfies every clause in a formula.

    Args:
        formula: 3-CNF formula encoded as signed integer literals.
        assignment: Truth value for each variable in the formula.

    Returns:
        True when every clause contains at least one true literal.
    """

    return all(any(assignment.get(abs(literal)) == (literal > 0) for literal in clause) for clause in formula)


def find_satisfying_assignment(formula: list[list[int]],
                               num_variables: int) -> dict[int, bool] | None:
    """Find a satisfying assignment for a formula when one exists.

    Args:
        formula: 3-CNF formula encoded as signed integer literals.
        num_variables: Number of variables in the formula.

    Returns:
        A satisfying complete assignment or None when the formula is unsatisfiable.
    """

    def simplify(clauses: list[list[int]],
                 assignment: dict[int, bool]) -> list[list[int]] | None:
        simplified_clauses = []
        for clause in clauses:
            simplified_clause = []
            for literal in clause:
                value = assignment.get(abs(literal))
                if value is None:
                    simplified_clause.append(literal)
                elif value == (literal > 0):
                    break
            else:
                if not simplified_clause:
                    return None
                simplified_clauses.append(simplified_clause)
        return simplified_clauses

    def solve(clauses: list[list[int]],
              assignment: dict[int, bool]) -> dict[int, bool] | None:
        clauses = simplify(clauses, assignment)
        if clauses is None:
            return None
        while clauses:
            unit_literals = [clause[0] for clause in clauses if len(clause) == 1]
            literals = {literal for clause in clauses for literal in clause}
            pure_literals = [literal for literal in literals if -literal not in literals]
            implied_literals = unit_literals or pure_literals
            if not implied_literals:
                break

            assignment = assignment.copy()
            for literal in implied_literals:
                variable = abs(literal)
                value = literal > 0
                if variable in assignment and assignment[variable] != value:
                    return None
                assignment[variable] = value
            clauses = simplify(clauses, assignment)
            if clauses is None:
                return None

        if not clauses:
            return assignment

        variable_counts = {}
        for clause in clauses:
            for literal in clause:
                variable = abs(literal)
                variable_counts[variable] = variable_counts.get(variable, 0) + 1
        variable = max(variable_counts, key=lambda key: (variable_counts[key], -key))
        for value in [False, True]:
            branch_assignment = assignment.copy()
            branch_assignment[variable] = value
            solution = solve(clauses, branch_assignment)
            if solution is not None:
                return solution
        return None

    solution = solve(formula, {})
    if solution is None:
        return None
    return {variable: solution.get(variable, False) for variable in range(1, num_variables + 1)}


def find_nearest_satisfying_assignment(formula: list[list[int]],
                                       num_variables: int,
                                       reference_assignment: dict[int, bool]) -> tuple[dict[int, bool] | None, int | None]:
    """Find a satisfying assignment with minimum Hamming distance to a reference.

    Args:
        formula: 3-CNF formula encoded as signed integer literals.
        num_variables: Number of Boolean variables in the formula.
        reference_assignment: Complete assignment representing the initial menu.

    Returns:
        The nearest satisfying assignment and its edit distance, or two None values
        when the formula is unsatisfiable.

    Raises:
        ValueError: If the reference assignment does not define every variable.
    """

    expected_variables = set(range(1, num_variables + 1))
    if set(reference_assignment) != expected_variables:
        raise ValueError('Reference assignment must define every variable exactly once.')

    best_assignment = find_satisfying_assignment(formula, num_variables)
    if best_assignment is None:
        return None, None

    best_distance = sum(
        best_assignment[variable] != reference_assignment[variable]
        for variable in expected_variables
    )

    def simplify(clauses: list[list[int]],
                 assignment: dict[int, bool]) -> list[list[int]] | None:
        simplified_clauses = []
        for clause in clauses:
            simplified_clause = []
            for literal in clause:
                value = assignment.get(abs(literal))
                if value is None:
                    simplified_clause.append(literal)
                elif value == (literal > 0):
                    break
            else:
                if not simplified_clause:
                    return None
                simplified_clauses.append(simplified_clause)
        return simplified_clauses

    def propagate_units(clauses: list[list[int]],
                        assignment: dict[int, bool],
                        distance: int) -> tuple[list[list[int]] | None, dict[int, bool], int]:
        while clauses:
            unit_literals = [clause[0] for clause in clauses if len(clause) == 1]
            if not unit_literals:
                return clauses, assignment, distance

            assignment = assignment.copy()
            for literal in unit_literals:
                variable = abs(literal)
                value = literal > 0
                existing_value = assignment.get(variable)
                if existing_value is not None and existing_value != value:
                    return None, assignment, distance
                if existing_value is None:
                    assignment[variable] = value
                    distance += int(value != reference_assignment[variable])

            clauses = simplify(clauses, assignment)
            if clauses is None:
                return None, assignment, distance

        return clauses, assignment, distance

    def search(clauses: list[list[int]],
               assignment: dict[int, bool],
               distance: int) -> None:
        nonlocal best_assignment, best_distance

        clauses = simplify(clauses, assignment)
        if clauses is None or distance >= best_distance:
            return

        clauses, assignment, distance = propagate_units(clauses, assignment, distance)
        if clauses is None or distance >= best_distance:
            return

        if not clauses:
            completed_assignment = {
                variable: assignment.get(variable, reference_assignment[variable])
                for variable in expected_variables
            }
            best_assignment = completed_assignment
            best_distance = distance
            return

        variable_counts = {}
        for clause in clauses:
            for literal in clause:
                variable = abs(literal)
                variable_counts[variable] = variable_counts.get(variable, 0) + 1
        variable = max(variable_counts, key=lambda item: (variable_counts[item], -item))

        for value in [reference_assignment[variable], not reference_assignment[variable]]:
            branch_assignment = assignment.copy()
            branch_assignment[variable] = value
            branch_distance = distance + int(value != reference_assignment[variable])
            search(clauses, branch_assignment, branch_distance)

    search(formula, {}, 0)
    return best_assignment, best_distance


def find_satisfying_assignment_distance_counts(formula: list[list[int]],
                                               num_variables: int,
                                               reference_assignment: dict[int, bool]) -> dict[int, int]:
    """Count satisfying assignments at each Hamming distance.

    Args:
        formula: 3-CNF formula encoded as signed integer literals.
        num_variables: Number of variables in the formula.
        reference_assignment: Complete assignment representing the initial menu.

    Returns:
        Number of satisfying assignments at each distance from the reference assignment.

    Raises:
        ValueError: If the reference assignment does not define every variable.
    """

    expected_variables = set(range(1, num_variables + 1))
    if set(reference_assignment) != expected_variables:
        raise ValueError('Reference assignment must define every variable exactly once.')

    distance_counts = {}
    for assignment_bits in range(1 << num_variables):
        assignment = {
            variable: bool(assignment_bits & (1 << (variable - 1)))
            for variable in expected_variables
        }
        if not is_satisfying_assignment(formula, assignment):
            continue

        distance = sum(
            assignment[variable] != reference_assignment[variable]
            for variable in expected_variables
        )
        distance_counts[distance] = distance_counts.get(distance, 0) + 1

    return distance_counts


def find_greedy_trap(formula: list[list[int]],
                     num_variables: int,
                     reference_assignment: dict[int, bool],
                     max_changes_per_turn: int,
                     min_greedy_remaining_distance: int,
                     min_greedy_excess_edits: int) -> dict | None:
    """Find a repair landscape where every locally greedy first update is costly.

    Args:
        formula: 3-CNF formula encoded as signed integer literals.
        num_variables: Number of Boolean variables in the formula.
        reference_assignment: Complete assignment representing the initial menu.
        max_changes_per_turn: Maximum variables that one repair update may change.
        min_greedy_remaining_distance: Required remaining distance from every greedy
            update to a solution.
        min_greedy_excess_edits: Required total-edit penalty for every greedy update
            relative to the optimal repair distance.

    Returns:
        Metadata for a repair landscape where every first update that maximises
        immediate satisfaction remains globally distant, while a less attractive
        first update starts an optimal path. Returns None when no such landscape
        exists.

    Raises:
        ValueError: If the reference assignment does not define every variable.
    """

    expected_variables = set(range(1, num_variables + 1))
    if set(reference_assignment) != expected_variables:
        raise ValueError('Reference assignment must define every variable exactly once.')

    reference_bits = sum(
        1 << (variable - 1)
        for variable in expected_variables
        if reference_assignment[variable]
    )
    satisfaction_counts = {}
    satisfying_assignments = []
    for assignment_bits in range(1 << num_variables):
        assignment = {
            variable: bool(assignment_bits & (1 << (variable - 1)))
            for variable in expected_variables
        }
        satisfaction_count = sum(
            any(assignment[abs(literal)] == (literal > 0) for literal in clause)
            for clause in formula
        )
        satisfaction_counts[assignment_bits] = satisfaction_count
        if satisfaction_count == len(formula):
            satisfying_assignments.append(assignment_bits)

    if not satisfying_assignments:
        return None

    update_masks = []
    for change_count in range(1, max_changes_per_turn + 1):
        for variables in combinations(range(num_variables), change_count):
            update_masks.append(sum(1 << variable for variable in variables))

    initial_satisfaction = satisfaction_counts[reference_bits]
    first_updates = []
    for update_mask in update_masks:
        updated_bits = reference_bits ^ update_mask
        solution_distance = min(
            (updated_bits ^ satisfying_assignment).bit_count()
            for satisfying_assignment in satisfying_assignments
        )
        first_updates.append({
            'mask': update_mask,
            'satisfaction': satisfaction_counts[updated_bits],
            'solution_distance': solution_distance
        })

    optimal_edit_distance = min(
        (reference_bits ^ satisfying_assignment).bit_count()
        for satisfying_assignment in satisfying_assignments
    )
    best_first_satisfaction = max(update['satisfaction'] for update in first_updates)
    greedy_updates = [update for update in first_updates
                      if update['satisfaction'] == best_first_satisfaction]
    if best_first_satisfaction <= initial_satisfaction:
        return None
    if any(
            update['solution_distance'] < min_greedy_remaining_distance
            or update['mask'].bit_count() + update['solution_distance']
            < optimal_edit_distance + min_greedy_excess_edits
            for update in greedy_updates):
        return None

    optimal_satisfying_assignments = [
        satisfying_assignment
        for satisfying_assignment in satisfying_assignments
        if (reference_bits ^ satisfying_assignment).bit_count() == optimal_edit_distance
    ]
    minimum_possible_turns = (
        optimal_edit_distance + max_changes_per_turn - 1
    ) // max_changes_per_turn
    remaining_edit_budget = (minimum_possible_turns - 1) * max_changes_per_turn
    optimal_first_updates = []
    for update in first_updates:
        updated_bits = reference_bits ^ update['mask']
        optimal_solution_distance = min(
            (updated_bits ^ satisfying_assignment).bit_count()
            for satisfying_assignment in optimal_satisfying_assignments
        )
        if (optimal_solution_distance <= remaining_edit_budget
                and update['satisfaction'] < best_first_satisfaction):
            optimal_first_updates.append({
                **update,
                'optimal_solution_distance': optimal_solution_distance
            })
    if not optimal_first_updates:
        return None

    return {
        'initial_satisfaction': initial_satisfaction,
        'best_first_satisfaction': best_first_satisfaction,
        'greedy_updates': [
            {
                'variables': [
                    variable + 1
                    for variable in range(num_variables)
                    if update['mask'] & (1 << variable)
                ],
                'solution_distance': update['solution_distance'],
                'total_edits_to_solution': (
                    update['mask'].bit_count() + update['solution_distance']
                )
            }
            for update in greedy_updates
        ],
        'optimal_first_updates': [
            {
                'variables': [
                    variable + 1
                    for variable in range(num_variables)
                    if update['mask'] & (1 << variable)
                ],
                'satisfaction': update['satisfaction'],
                'optimal_solution_distance': update['optimal_solution_distance']
            }
            for update in optimal_first_updates
        ]
    }


def find_unsatisfying_assignment(formula: list[list[int]],
                                 num_variables: int) -> dict[int, bool]:
    """Find a complete assignment that does not satisfy a formula.

    Args:
        formula: 3-CNF formula encoded as signed integer literals.
        num_variables: Number of variables in the formula.

    Returns:
        A complete assignment that leaves at least one clause unsatisfied.

    Raises:
        ValueError: If every assignment satisfies the formula.
    """

    for clause in formula:
        assignment = {variable: False for variable in range(1, num_variables + 1)}
        clause_assignment = {}
        for literal in clause:
            variable = abs(literal)
            value = literal < 0
            if variable in clause_assignment and clause_assignment[variable] != value:
                break
            clause_assignment[variable] = value
        else:
            assignment.update(clause_assignment)
            return assignment
    raise ValueError('Formula has no unsatisfying assignment.')


def is_satisfiable(formula: list[list[int]],
                   num_variables: int) -> bool:
    """Determine whether a formula has at least one satisfying assignment.

    Args:
        formula: 3-CNF formula encoded as signed integer literals.
        num_variables: Number of Boolean variables in the formula.

    Returns:
        True when at least one complete assignment satisfies the formula.
    """

    return find_satisfying_assignment(formula, num_variables) is not None
